import type { Job } from "@/types/jobs/jobs";

export const jobs = [
  {
    id: 1,
    posted_by_user_id: 2,
    title: "Frontend Developer",
    company_name: "TechCorp",
    location: "Bangalore",
    workplace_type: "remote",
    job_type: "full-time",
    min_salary: 600000,
    max_salary: 900000,
    currency: "INR",
    experience_level: "junior",
    description: "Build responsive UI using React and Tailwind.",
    requirements: [
      "Strong JS fundamentals",
      "React experience",
      "Git knowledge",
    ],
    responsibilities: [
      "Build and maintain UI components",
      "Collaborate with designers and backend engineers",
      "Optimize performance and accessibility",
    ],
    application_deadline: "2026-04-30",
    people_applied: 18,
    status: "open",
    created_at: "2026-03-10T10:00:00.000Z",
    updated_at: "2026-03-12T10:00:00.000Z",
  },
  {
    id: 2,
    posted_by_user_id: 3,
    title: "Backend Developer",
    company_name: "CodeBase",
    location: "Hyderabad",
    workplace_type: "hybrid",
    job_type: "full-time",
    min_salary: 800000,
    max_salary: 1200000,
    currency: "INR",
    experience_level: "intermediate",
    description: "Develop scalable APIs using Node.js and PostgreSQL.",
    requirements: ["Node.js", "SQL", "REST APIs"],
    responsibilities: [
      "Design and implement REST APIs",
      "Write clean, testable backend code",
      "Work with the database schema and queries",
    ],
    application_deadline: "2026-05-10",
    people_applied: 42,
    status: "open",
    created_at: "2026-03-08T10:00:00.000Z",
    updated_at: "2026-03-14T10:00:00.000Z",
  },
  {
    id: 3,
    posted_by_user_id: 4,
    title: "Full Stack Developer",
    company_name: "InnovateX",
    location: "Remote",
    workplace_type: "remote",
    job_type: "full-time",
    min_salary: 1000000,
    max_salary: 1500000,
    currency: "INR",
    experience_level: "senior",
    description: "Work across frontend and backend systems.",
    requirements: ["React", "Node.js", "System design"],
    responsibilities: [
      "Build end-to-end features across the stack",
      "Review code and mentor engineers",
      "Own system design and technical decisions",
    ],
    application_deadline: "2026-05-20",
    people_applied: 63,
    status: "open",
    created_at: "2026-03-05T10:00:00.000Z",
    updated_at: "2026-03-15T10:00:00.000Z",
  },
  {
    id: 4,
    posted_by_user_id: 2,
    title: "UI/UX Designer",
    company_name: "Designify",
    location: "Mumbai",
    workplace_type: "on-site",
    job_type: "full-time",
    min_salary: 500000,
    max_salary: 800000,
    currency: "INR",
    experience_level: "junior",
    description: "Design modern and user-friendly interfaces.",
    requirements: ["Figma", "User research", "Wireframing"],
    responsibilities: [
      "Create user flows, wireframes and prototypes",
      "Run user research and iterate on findings",
      "Collaborate with engineers to ship polished UX",
    ],
    application_deadline: "2026-04-25",
    people_applied: 25,
    status: "open",
    created_at: "2026-03-09T10:00:00.000Z",
    updated_at: "2026-03-16T10:00:00.000Z",
  },
  {
    id: 5,
    posted_by_user_id: 5,
    title: "DevOps Engineer",
    company_name: "CloudOps",
    location: "Pune",
    workplace_type: "hybrid",
    job_type: "full-time",
    min_salary: 900000,
    max_salary: 1400000,
    currency: "INR",
    experience_level: "intermediate",
    description: "Manage CI/CD pipelines and cloud infra.",
    requirements: ["AWS", "Docker", "CI/CD"],
    responsibilities: [
      "Maintain CI/CD pipelines",
      "Improve reliability and observability",
      "Automate infrastructure provisioning",
    ],
    application_deadline: "2026-05-15",
    people_applied: 37,
    status: "open",
    created_at: "2026-03-04T10:00:00.000Z",
    updated_at: "2026-03-17T10:00:00.000Z",
  },
  {
    id: 6,
    posted_by_user_id: 6,
    title: "Data Analyst",
    company_name: "DataWorks",
    location: "Delhi",
    workplace_type: "on-site",
    job_type: "full-time",
    min_salary: 400000,
    max_salary: 700000,
    currency: "INR",
    experience_level: "fresher",
    description: "Analyze datasets and generate insights.",
    requirements: ["SQL", "Excel", "Data visualization"],
    responsibilities: [
      "Create dashboards and reports",
      "Translate business questions into analysis",
      "Maintain data quality checks",
    ],
    application_deadline: "2026-04-28",
    people_applied: 11,
    status: "open",
    created_at: "2026-03-11T10:00:00.000Z",
    updated_at: "2026-03-18T10:00:00.000Z",
  },
  {
    id: 7,
    posted_by_user_id: 3,
    title: "Mobile App Developer",
    company_name: "Appify",
    location: "Remote",
    workplace_type: "remote",
    job_type: "contract",
    min_salary: 700000,
    max_salary: 1100000,
    currency: "INR",
    experience_level: "intermediate",
    description: "Build cross-platform mobile apps.",
    requirements: ["React Native", "API integration", "Debugging"],
    responsibilities: [
      "Build features in React Native",
      "Integrate APIs and handle offline states",
      "Ship releases and fix production bugs",
    ],
    application_deadline: "2026-05-18",
    people_applied: 29,
    status: "open",
    created_at: "2026-03-06T10:00:00.000Z",
    updated_at: "2026-03-19T10:00:00.000Z",
  },
  {
    id: 8,
    posted_by_user_id: 4,
    title: "QA Engineer",
    company_name: "Testify",
    location: "Chennai",
    workplace_type: "hybrid",
    job_type: "full-time",
    min_salary: 500000,
    max_salary: 800000,
    currency: "INR",
    experience_level: "junior",
    description: "Ensure product quality through testing.",
    requirements: [
      "Manual testing",
      "Automation basics",
      "Attention to detail",
    ],
    responsibilities: [
      "Write and execute test plans",
      "Automate critical regression flows",
      "Report bugs with clear reproduction steps",
    ],
    application_deadline: "2026-04-27",
    people_applied: 34,
    status: "open",
    created_at: "2026-03-07T10:00:00.000Z",
    updated_at: "2026-03-20T10:00:00.000Z",
  },
  {
    id: 9,
    posted_by_user_id: 5,
    title: "Product Manager",
    company_name: "Prodify",
    location: "Bangalore",
    workplace_type: "on-site",
    job_type: "full-time",
    min_salary: 1200000,
    max_salary: 1800000,
    currency: "INR",
    experience_level: "senior",
    description: "Lead product development and strategy.",
    requirements: ["Product thinking", "Communication", "Agile"],
    responsibilities: [
      "Define product roadmap and priorities",
      "Coordinate cross-functional execution",
      "Measure outcomes and iterate",
    ],
    application_deadline: "2026-05-25",
    people_applied: 58,
    status: "open",
    created_at: "2026-03-02T10:00:00.000Z",
    updated_at: "2026-03-21T10:00:00.000Z",
  },
  {
    id: 10,
    posted_by_user_id: 2,
    title: "Intern Software Developer",
    company_name: "StartupHub",
    location: "Remote",
    workplace_type: "remote",
    job_type: "internship",
    min_salary: 150000,
    max_salary: 300000,
    currency: "INR",
    experience_level: "fresher",
    description: "Assist in building web applications.",
    requirements: ["Basic JS", "HTML/CSS", "Learning mindset"],
    responsibilities: [
      "Assist with feature implementation",
      "Fix small bugs and write small improvements",
      "Learn team workflows and best practices",
    ],
    application_deadline: "2026-04-22",
    people_applied: 9,
    status: "open",
    created_at: "2026-03-13T10:00:00.000Z",
    updated_at: "2026-03-22T10:00:00.000Z",
  },
] satisfies Job[];
